config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'
  resources :posts, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Rubik+Glitch&display=swap" rel="stylesheet">
  </head>

  <body>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    
    <div class="grid-container">
      <div class="nav post-controls">
        <% if user_signed_in? %>
          <%= link_to "New Post", new_post_path, class: "button new-post" %>
        <% end %>
      </div>
      <div class="nav brand">
        <%= link_to "Members Only!", root_path %>
      </div>
      <div class="nav session-controls">
        <% if user_signed_in? %>
          <%= link_to current_user.name, edit_user_registration_path %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %>
          <%= link_to "Sign in", new_user_session_path %>
        <% end %>
      </div>
      <div class="main-container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_feed.html.erb
<div class="feed">
  <div class="posts-container">
    <% @posts.each do |post| %>
      <div class="post-container">
        <h3 class="title"><%= post.title %></h3>
        <p class="body"><%= post.body %></p>
        <% if user_signed_in? %>
          <p>-<%= post.user.name %></p>
        <% else %>
          <p>-Anonymous</p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="index">
  <% unless user_signed_in? %>
    <div class="info">
      <p>To see who is posting or join in on the conversation, you must first sign in or create an account!
    </div>
  <% end %>
  <%= render 'feed' %>
</div>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-container">
  <h2>New post!</h2>

  <%= form_with model: @post do |f| %>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 20 %>
    </div>
    <%= f.submit "Post", class: "button" %>
  <% end %>
</div>